export const GAME_CONFIG = {
  lanes: 4,
  laneWidth: 120,
  canvasPadding: 16,
  playfieldHeight: 1000,
  player: {
    width: 32,
    height: 48,
    moveDuration: 150,
    fireCooldown: 220,
    minFireCooldown: 90,
    maxHealth: 5,
    projectileSpeed: 760,
    projectileSpeedMax: 1080,
    spreadStep: 0.12,
    maxSpread: 0.32,
    autoAimStrength: 1.6,
  },
  projectile: {
    width: 8,
    height: 24,
    autoAimTurnRate: 5.4,
  },
  enemy: {
    width: 28,
    height: 38,
    baseSpeed: 180,
    maxSpeed: 540,
    spawnInterval: 950,
    minSpawnInterval: 320,
    burstSpawnCount: 6,
    burstMultiplier: 2.1,
    burstInterval: 12000,
    burstDuration: 2200,
  },
  difficulty: {
    rampInterval: 10000,
    rampFactor: 0.92,
    scorePerSecond: 5,
    scorePerEnemy: 25,
    burstRamp: 0.1,
    maxEnemies: 64,
  },
  damage: {
    onHit: 1,
    onLeak: 1,
  },
  powerUps: {
    dropChance: 0.08,
    dropRamp: 0.015,
    maxActive: 8,
    gravity: 280,
    magnetRadius: 180,
    collectRadius: 44,
  },
};

export const UI_CONFIG = {
  mobileBreakpoint: 920,
};
